import Head from 'next/head';
import styles from 'styles/Home.module.scss';
import { useEffect, useState } from 'react';
import WebSocket from 'isomorphic-ws';
import { JSONPricesType } from 'types/prices.types';

import { SelectExchange, ExchangesContainer, SelectQuantity } from 'components';

export default function Home() {
  const [exchanges, setExchanges] = useState<JSONPricesType>([]);
  const [selectedExchange, setSelectedExchange] = useState<string>('');
  const [showQuantity, setShowQuantity] = useState<string>('');

  const ws = new WebSocket('wss://wssx.gntapi.com:443');

  useEffect(() => {
    ws.onopen = () => {
      ws.send('prices');
    };

    ws.onmessage = function (event: any) {
      const json = JSON.parse(event.data);
      try {
        if ((json.event = 'data')) {
          setExchanges(json.prices);
        }
      } catch (err) {
        console.log('error: ', err);
      }
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1>Visualizador de precios GNT</h1>

        <SelectExchange
          exchanges={exchanges}
          setSelectedExchange={setSelectedExchange}
          setShowQuantity={setShowQuantity}
        />

        <SelectQuantity
          exchanges={exchanges}
          setShowQuantity={setShowQuantity}
        />

        {exchanges && (
          <ExchangesContainer
            exchanges={exchanges}
            selectedExchange={selectedExchange}
            showQuantity={showQuantity}
          />
        )}
      </main>
    </>
  );
}
